### ISSUE TITLE
Incorrect iteration over large elements

### ISSUE THREAD

**Issue by 197g** [austinleroy/ebml-iterable#1]
I'm having trouble reading back some data written with the library (mkv in this case). This seems to happen if one element exceeds the default buffer size of the reader; and this element is not the last element in its parent master element; and that master element is towards the end of the file.

Reproduce with this minimize program:

```
    use ebml_iterable::specs::{ebml_specification, TagDataType, Master};
    
    #[ebml_specification]
    #[derive(Clone, Debug, PartialEq)]
    pub enum Trial {
        #[id(0x18538067)]
        #[data_type(TagDataType::Master)]
        Segment,

        #[id(0x1F43B675)]
        #[data_type(TagDataType::Master)]
        Cluster,

        #[id(0x4100)]
        #[data_type(TagDataType::UnsignedInt)]
        Count,

        #[id(0xa1)]
        #[data_type(TagDataType::Binary)]
        Block,
    }

    #[test]
    pub fn roundtrip() {
        use ebml_iterable::{TagIterator, TagWriter};
        use std::io::Cursor;
        let mut dest = Cursor::new(Vec::new());
        let mut writer = TagWriter::new(&mut dest);

        writer.write(&Trial::Segment(Master::Start)).expect("Error writing tag");
        writer.write(&Trial::Cluster(Master::Start)).expect("Error writing tag");
        // Why 0x10001 specifically? This exceeds the default buffer length (0x10000)?!
        writer.write_raw(0xa1, &[0x00; 0x10001]).expect("Error writing tag");
        writer.write(&Trial::Count(0x00)).expect("Error writing tag");
        writer.write(&Trial::Cluster(Master::End)).expect("Error writing tag");
        writer.write(&Trial::Segment(Master::End)).expect("Error writing tag");
        drop(writer);

        dest.set_position(0);
        let iter = TagIterator::<_, Trial>::new(dest, &[]);

        let tags: Vec<_> = iter.into_iter().collect();
        assert_eq!(tags.len(), 4+2, "Reading every tag that was written");
   }
```

While scouting code I found one suspicious line:
https://github.com/austinleroy/ebml-iterable/blob/4247ca7431ec4a087a0a348b425ac0a55703a5ce/src/tag_iterator.rs#L251

If I understand correctly this tries to read at least `self.internal_buffer_position` more bytes of data. It's also called _after_ that `0xa1` element and the internal buffer position is `65555` at that point. This will surely result in fully reading the file, then getting an empty read, and then returning `Ok(false)`—which in turn is interpreted as being done even though the tag was not finished.

To trigger this failure condition the large element must end at a full buffer, exactly, and at the same time less than a full buffer worth of data must be remaining in the file.

**Comment by austinleroy** [comment]
Thanks for bringing this to my attention!  Sorry that it's been a few days.  I added a few tests and pushed an update that should resolve the specific issue you were seeing.  Your example and research were incredibly helpful!

Thank you again, and let me know if you find any other issues.
