### ISSUE TITLE
`ToolError` is unnameable from outside

### ISSUE THREAD

**Issue by andylizi** [austinleroy/ebml-iterable#2]
https://github.com/austinleroy/ebml-iterable/blob/37e160c38f1a78a7f006d124fa808a772be7b0a9/src/errors.rs#L67-L78

One of the variants of `TagIteratorError` uses the `ToolError` type, but the latter is not exported, making it "unnamable" from outside. This is the kind of situation described in rust-lang/rust#34537. I'd like to access data stored in this error, but there's no way to extract it.

Can you consider exporting `ToolError` (and maybe reexport it in `webm-iterable`)?

**Comment by austinleroy** [comment]
Thanks for bringing this to my attention! The fact that it wasn't already exported was simply an oversight.  I will make the change and push up version 0.3.2 to resolve this.
